name: Build

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B formatter:validate verify --file pom.xml

    - name: Store PR id
      run: echo ${{ github.event.number }} > ./docs/target/generated-docs/pr-id.txt
      if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'

    - name: Publishing directory for PR preview
      uses: actions/upload-artifact@v3
      if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
      with:
        name: site
        path: ./docs/target/generated-docs
        retention-days: 3
