name: Quarkiverse Release

on:
  pull_request:
    types: [closed]
    paths:
      - '.github/project.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    name: release
    if: ${{github.event.pull_request.merged == true}}

    steps:
      - uses: radcortez/project-metadata-action@1.0
        name: Retrieve project metadata
        id: metadata
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          metadata-file-path: '.github/project.yml'

      - uses: actions/checkout@v3

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Configure Git author
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Maven release ${{steps.metadata.outputs.current-version}}
        run: |
          git checkout -b release
          mvn -B release:prepare -Prelease -DreleaseVersion=${{steps.metadata.outputs.current-version}} -DdevelopmentVersion=${{steps.metadata.outputs.next-version}}
          git commit -am "Update stable version for documentation"
          git checkout ${{github.base_ref}}
          git rebase release
          mvn -B release:perform -Darguments=-DperformRelease -DperformRelease -Prelease
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

      - name: Adjust tag for documentation changes
        run: |
          git checkout ${{steps.metadata.outputs.current-version}}
          mvn -B clean install -DskipTests -DskipITs
          git commit -am "Update stable version for documentation"
          # Move the tag after inclusion of documentation adjustments
          git tag -f ${{steps.metadata.outputs.current-version}}
          # Push modified tag
          git push origin refs/tags/${{steps.metadata.outputs.current-version}} -f
          # Go back to base ref
          git checkout ${{github.base_ref}}

      - name: Push changes
        run: git push
